In [1]:
# Copyright (c) 2017 WasteNot
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl
import scipy
from sklearn import linear_model
import datetime

%matplotlib inline

In [3]:
# Features: Date, What they bought, How much food did the customer throw away, inventory leftover
# Weather, Season, Holiday events, Location of restaurant

In [4]:
food_to_ing_dict = {
    'Salad': {
        ('lettuce', 300),
        ('tomato', 50),
        ('cucumber', 50)
    },
    'Cheese Burger': {
        ('flour', 100),
        ('cheese', 20),
        ('beef', 500),
        ('lettuce', 10),
        ('tomato', 10)
    },
    'Pizza': {
        ('cheese', 300),
        ('tomato', 50),
        ('flour', 300),
        ('pepperoni', 100)
    }
}

In [5]:
season_to_num_dict = {
    'Spring': 0,
    'Summer': 1,
    'Fall': 2,
    'Winter': 3
}

In [6]:
# Columns:
# Year,Month,Day,Lunch/Dinner(0,1),Season(Spring,Summer,Autumn,Winter),Number of People(int),temp(int),Wind Speed(int Km/h),Humidity(%),Precipitation(%),Food (Salad,Cheese Burger,Pizza)
# 2017,1,1,0,"Spring",2,28,21,0.46,0.15,"Salad",

In [7]:
data = np.genfromtxt('food.csv', delimiter=',', dtype=np.str)
features = data[:, :-1]
for key in season_to_num_dict.keys():
    features[np.where(features == key)] = season_to_num_dict[key]

In [8]:
output_raw = data[:, -1]
# lettuce, tomato, cucumber, flour, cheese, beef, pepperoni
outputs_arr = ['lettuce', 'tomato', 'cucumber', 'flour', 'cheese', 'beef', 'pepperoni']
output = np.zeros((len(data), 7))
for idx, food in enumerate(output_raw):
    ing_set = food_to_ing_dict[food]
    for name, quantity in ing_set:
        output_arr_idx = outputs_arr.index(name)
        output[idx, output_arr_idx] += quantity

num_days = 10
today = datetime.date.today()
today_m = today.month
today_d = today.day
next_date = today + datetime.timedelta(days=num_days)
next_date_m = next_date.month
next_date_d = next_date.day

In [9]:
print(outputs_arr)
for i in range(12):
    idx = np.where(features[:, 1].astype(np.int) == (i + 1))
    input_features = features[idx].astype(np.float)
    
    model = skl.linear_model.Ridge(fit_intercept=True, normalize=True, copy_X=True, alpha=0.1)
    model.fit(features, output)
    res = model.predict(input_features)
    res = res.astype(np.int)
    res = np.sum(res, axis=0)
    print(res)

['lettuce', 'tomato', 'cucumber', 'flour', 'cheese', 'beef', 'pepperoni']
[17052  7599  2672 31467 27354 25643  8708]
[15973  7112  2506 29509 25626 24190  8162]
[15163  6838  2383 28566 24815 23338  7899]
[15103  6711  2376 27821 24115 23067  7671]
[12571  4961  1978 19239 16406 17717  5178]
[12524  4999  1981 19510 16630 17922  5266]
[12291  4995  1930 19758 16883 17892  5345]
[11672  4683  1838 18368 15655 16880  4950]
[12558  5016  1976 19647 16703 18273  5280]
[11958  4825  1885 19027 16208 17540  5122]
[ 9655  3988  1526 15930 13612 14449  4309]
[12436  5077  1952 20184 17186 18740  5436]
